version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  go-image-store-service:
    build: .
    container_name: Go-image-store-service
    restart: always
    ports: 
      - 8080:8080
    depends_on: 
      - kafka
    volumes:
      - /home/wrongaxe/go/src/github.com/balasiddhartha-t/image-store-service/Albums:/app/Albums
